### PR TITLE
Add a simple CI that builds the whole project

### PR DESCRIPTION
**Pull request by ylatuya**

### CODE REVIEW

**Comment by thiblahute** [comment]
Any idea why the `checks` is empty?

**Comment by ylatuya** [comment]
I have no idea, it's the first time I setup a CI pipeline using GitHub Actions, I will have to check the docs to see how it should work.
What I can see is that Actions are run in my fork, but not here for example.

**Comment by ylatuya** [comment]
Fixed, it's done automatically with the event "pull_request" which was missing.

**Comment by ylatuya** [comment]
@thiblahute  you should also enable "Run workflows from fork pull requests"

**Comment by ylatuya** [comment]
See https://github.com/ylatuya/GtkSharp/pull/1 for a reference

**Comment by thiblahute** [comment]
I set " Require approval for first-time contributors who are new to GitHub " and it didn't start the workflow, also I don't get why it is not even visible tbh, any idea?

**Comment by ylatuya** [comment]
I have no idea, it's probably related to the fact that it's the first time it's added and it's done from a fork. Can you try creating a PR yourself from the same branch in this repo?

**Comment by thiblahute** [comment]
Closing as https://github.com/GLibSharp/GtkSharp/pull/57 has been merged instead.

**Pull request closed without merging**
